name: Deploy to Amazon EKS
on:
  push:
    branches: [ "main" ] 

env:
  AWS_REGION: ap-southeast-1
  EKS_CLUSTER_NAME: casino-app-cluster
  ECR_REPOSITORY: casino-app
  IAM_ROLE_ARN: ${{secrets.AWS_ROLE_ARN}}

permissions:
  id-token: write # Bắt buộc để dùng OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Đăng nhập AWS bằng IAM Role (OIDC)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          aws-region: ${{env.AWS_REGION }}

      # Đăng nhập ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build & Push Image (Dùng hash commit làm tag để tránh trùng lặp)
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/${{env.ECR_REPOSITORY}}:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{env.ECR_REPOSITORY}}:$IMAGE_TAG
          echo "FULL_IMAGE_NAME=$ECR_REGISTRY/${{env.ECR_REPOSITORY}}:$IMAGE_TAG" >> $GITHUB_ENV

      # Bơm Secret vào file YAML và Deploy
      - name: Inject Secrets and Deploy to EKS
        env:
          DB_PASSWORD_PLAIN: ${{ secrets.DB_PASSWORD_PLAIN }}
          MAIL_PASSWORD_PLAIN: ${{ secrets.MAIL_PASSWORD_PLAIN }}
        run: |
          envsubst < k8s-config/01-secret.yaml > k8s-config/01-secret.yaml.tmp && mv k8s-config/01-secret.yaml.tmp k8s-config/01-secret.yaml
          
          envsubst < k8s-config/04-app-setup.yaml > k8s-config/04-app-setup.yaml.tmp && mv k8s-config/04-app-setup.yaml.tmp k8s-config/04-app-setup.yaml
          
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }} 

          kubectl apply -f k8s-config/